// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD56me6cNcvEnXs5O1ojEO_uTc66aBC0wM',
    appId: '1:533769859648:ios:c121b344cf61bf0650e5a5',
    messagingSenderId: '533769859648',
    projectId: 'midterm-demo-63112',
    storageBucket: 'midterm-demo-63112.firebasestorage.app',
    iosBundleId: 'com.example.midtermDemo',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIq6zk91D6y0JNo6gqOAKg67bG3gmzaUE',
    appId: '1:533769859648:web:cfa4a128b1d19bed50e5a5',
    messagingSenderId: '533769859648',
    projectId: 'midterm-demo-63112',
    authDomain: 'midterm-demo-63112.firebaseapp.com',
    storageBucket: 'midterm-demo-63112.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD56me6cNcvEnXs5O1ojEO_uTc66aBC0wM',
    appId: '1:533769859648:ios:c121b344cf61bf0650e5a5',
    messagingSenderId: '533769859648',
    projectId: 'midterm-demo-63112',
    storageBucket: 'midterm-demo-63112.firebasestorage.app',
    iosBundleId: 'com.example.midtermDemo',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeWsCnFOWsZ0PYCxW98SUdq31JIh7o9aM',
    appId: '1:533769859648:android:799d748ef07b2a2550e5a5',
    messagingSenderId: '533769859648',
    projectId: 'midterm-demo-63112',
    storageBucket: 'midterm-demo-63112.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIq6zk91D6y0JNo6gqOAKg67bG3gmzaUE',
    appId: '1:533769859648:web:330db7642f7d9dd750e5a5',
    messagingSenderId: '533769859648',
    projectId: 'midterm-demo-63112',
    authDomain: 'midterm-demo-63112.firebaseapp.com',
    storageBucket: 'midterm-demo-63112.firebasestorage.app',
  );

}